language: csharp
solution: LineBot.sln

sudo: required

branches:
  only:
    - master

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
      dist: trusty

script:
  - dotnet restore
  - dotnet build LineBot.sln -c Release
  - dotnet test tests/LineBot.Tests/LineBot.Tests.csproj --no-build -c Release