name: $(Date:yyyyMMdd.HHmm)

jobs:
- job: Windows
  queue: 'Hosted VS2017'
  steps:
  - template: build/build.yml

- job: Linux
  queue: 'Hosted Linux Preview'
  steps:
  - template: build/build.yml

- job: macOS
  queue: 'Hosted macOS Preview'
  steps:
  - template: build/build.yml