name: $(Date:yyyyMMdd.HHmm)

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: build/build.yml
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage results'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)\tests\LineBot.Tests\coverage.cobertura.xml'

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: build/build.yml

- job: macOS
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - template: build/build.yml