on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main
jobs:
  LineBot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore --configuration Release --verbosity normal

      - name: Pack
        run: dotnet pack --no-restore --configuration Release --output .

      - uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: '*.nupkg'
