on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal
